vich_uploader:
    db_driver: orm
 
    metadata:
        type: attribute
 
    mappings:
        house:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer